# Generated by Django 5.2.7 on 2025-11-02 08:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentKPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation_year', models.IntegerField(help_text='평가년도 (2023~2025)')),
                ('college', models.CharField(help_text='단과대학명', max_length=50)),
                ('department', models.CharField(help_text='학과명', max_length=50)),
                ('employment_rate', models.DecimalField(decimal_places=2, help_text='졸업생 취업률 (%) (0~100 범위)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fulltime_faculty_count', models.IntegerField(help_text='전임교원 수 (명)', validators=[django.core.validators.MinValueValidator(0)])),
                ('visiting_faculty_count', models.IntegerField(help_text='초빙교원 수 (명)', validators=[django.core.validators.MinValueValidator(0)])),
                ('tech_transfer_revenue', models.DecimalField(decimal_places=2, help_text='연간 기술이전 수입액 (억원)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('intl_conference_count', models.IntegerField(help_text='국제학술대회 개최 횟수', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'department_kpi',
                'indexes': [models.Index(fields=['evaluation_year', 'department'], name='idx_department_kpi_year_dept'), models.Index(fields=['college'], name='idx_department_kpi_college'), models.Index(fields=['department'], name='idx_department_kpi_department'), models.Index(fields=['evaluation_year', 'employment_rate'], name='idx_dept_kpi_year_emp')],
                'constraints': [models.UniqueConstraint(fields=('evaluation_year', 'department'), name='unique_year_department'), models.CheckConstraint(condition=models.Q(('evaluation_year__gte', 2023), ('evaluation_year__lte', 2025)), name='check_evaluation_year_range'), models.CheckConstraint(condition=models.Q(('employment_rate__gte', 0), ('employment_rate__lte', 100)), name='check_employment_rate_range'), models.CheckConstraint(condition=models.Q(('fulltime_faculty_count__gte', 0)), name='check_fulltime_faculty_count_positive'), models.CheckConstraint(condition=models.Q(('visiting_faculty_count__gte', 0)), name='check_visiting_faculty_count_positive'), models.CheckConstraint(condition=models.Q(('tech_transfer_revenue__gte', 0)), name='check_tech_transfer_revenue_positive'), models.CheckConstraint(condition=models.Q(('intl_conference_count__gte', 0)), name='check_intl_conference_count_positive')],
            },
        ),
        migrations.CreateModel(
            name='PublicationList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publication_id', models.CharField(help_text='논문ID (고유 식별자, 예: PUB-23-001)', max_length=20, unique=True)),
                ('publication_date', models.DateField(help_text='게재일')),
                ('college', models.CharField(help_text='단과대학명', max_length=50)),
                ('department', models.CharField(help_text='학과명', max_length=50)),
                ('title', models.CharField(help_text='논문제목', max_length=500)),
                ('first_author', models.CharField(help_text='주저자명', max_length=100)),
                ('co_authors', models.CharField(blank=True, help_text='참여저자 (세미콜론(;)으로 구분)', max_length=500, null=True)),
                ('journal_name', models.CharField(help_text='학술지명', max_length=200)),
                ('journal_grade', models.CharField(choices=[('SCIE', 'SCIE'), ('KCI', 'KCI'), ('일반', '일반')], help_text='저널등급', max_length=20)),
                ('impact_factor', models.DecimalField(blank=True, decimal_places=2, help_text='Impact Factor (SCIE 논문만 해당)', max_digits=5, null=True)),
                ('project_linked', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], help_text='과제연계여부', max_length=1)),
            ],
            options={
                'db_table': 'publication_list',
                'indexes': [models.Index(fields=['publication_id'], name='idx_publication_list_pub_id'), models.Index(fields=['publication_date'], name='idx_publication_list_date'), models.Index(fields=['college', 'department'], name='idx_pub_list_col_dept'), models.Index(fields=['journal_grade'], name='idx_pub_list_jnl_grade'), models.Index(fields=['publication_date', 'journal_grade'], name='idx_pub_list_date_grade')],
                'constraints': [models.CheckConstraint(condition=models.Q(('journal_grade__in', ['SCIE', 'KCI', '일반'])), name='check_journal_grade_valid'), models.CheckConstraint(condition=models.Q(('project_linked__in', ['Y', 'N'])), name='check_project_linked_valid')],
            },
        ),
        migrations.CreateModel(
            name='ResearchProjectData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution_id', models.CharField(help_text='집행ID (고유 식별자, 예: T2301001)', max_length=20, unique=True)),
                ('project_number', models.CharField(help_text='과제번호', max_length=50)),
                ('project_name', models.CharField(help_text='과제명', max_length=200)),
                ('principal_investigator', models.CharField(help_text='연구책임자 (교수명)', max_length=100)),
                ('department', models.CharField(help_text='소속학과', max_length=50)),
                ('funding_agency', models.CharField(help_text='지원기관', max_length=100)),
                ('total_budget', models.BigIntegerField(help_text='총연구비 (원)', validators=[django.core.validators.MinValueValidator(0)])),
                ('execution_date', models.DateField(help_text='집행일자')),
                ('expense_item', models.CharField(help_text='집행항목', max_length=100)),
                ('expense_amount', models.BigIntegerField(help_text='집행금액 (원)', validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('집행완료', '집행완료'), ('처리중', '처리중'), ('반려', '반려')], help_text='상태', max_length=20)),
                ('notes', models.CharField(blank=True, help_text='비고', max_length=500, null=True)),
            ],
            options={
                'db_table': 'research_project_data',
                'indexes': [models.Index(fields=['execution_id'], name='idx_research_project_exec_id'), models.Index(fields=['project_number'], name='idx_research_project_number'), models.Index(fields=['department'], name='idx_research_project_dept'), models.Index(fields=['execution_date'], name='idx_research_project_date'), models.Index(fields=['status'], name='idx_research_project_status'), models.Index(fields=['funding_agency'], name='idx_res_proj_fund_agency'), models.Index(fields=['funding_agency', 'execution_date'], name='idx_res_proj_agency_date')],
                'constraints': [models.CheckConstraint(condition=models.Q(('total_budget__gte', 0)), name='check_total_budget_positive'), models.CheckConstraint(condition=models.Q(('expense_amount__gte', 0)), name='check_expense_amount_positive'), models.CheckConstraint(condition=models.Q(('status__in', ['집행완료', '처리중', '반려'])), name='check_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='StudentRoster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.CharField(help_text='학번 (고유 식별자)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='이름', max_length=50)),
                ('college', models.CharField(help_text='단과대학명', max_length=50)),
                ('department', models.CharField(help_text='학과명', max_length=50)),
                ('grade', models.IntegerField(help_text='학년 (0~4, 0은 대학원생)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('program_type', models.CharField(choices=[('학사', '학사'), ('석사', '석사'), ('박사', '박사')], help_text='과정구분', max_length=10)),
                ('academic_status', models.CharField(choices=[('재학', '재학'), ('휴학', '휴학'), ('졸업', '졸업'), ('제적', '제적')], help_text='학적상태', max_length=20)),
                ('gender', models.CharField(choices=[('남', '남'), ('여', '여')], help_text='성별', max_length=1)),
                ('admission_year', models.IntegerField(help_text='입학년도 (YYYY)', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('advisor', models.CharField(blank=True, help_text='지도교수 (대학원생의 경우 필수)', max_length=50, null=True)),
                ('email', models.CharField(help_text='이메일 주소', max_length=100)),
            ],
            options={
                'db_table': 'student_roster',
                'indexes': [models.Index(fields=['student_id'], name='idx_student_roster_student_id'), models.Index(fields=['college', 'department'], name='idx_stu_roster_col_dept'), models.Index(fields=['program_type'], name='idx_stu_roster_prog_type'), models.Index(fields=['academic_status'], name='idx_stu_roster_acad_status'), models.Index(fields=['email'], name='idx_student_roster_email')],
                'constraints': [models.CheckConstraint(condition=models.Q(('grade__gte', 0), ('grade__lte', 4)), name='check_grade_range'), models.CheckConstraint(condition=models.Q(('program_type__in', ['학사', '석사', '박사'])), name='check_program_type_valid'), models.CheckConstraint(condition=models.Q(('academic_status__in', ['재학', '휴학', '졸업', '제적'])), name='check_academic_status_valid'), models.CheckConstraint(condition=models.Q(('gender__in', ['남', '여'])), name='check_gender_valid'), models.CheckConstraint(condition=models.Q(('admission_year__gte', 2000), ('admission_year__lte', 2100)), name='check_admission_year_range')],
            },
        ),
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(help_text='업로드된 파일명', max_length=255)),
                ('data_type', models.CharField(choices=[('kpi', 'kpi'), ('publication', 'publication'), ('project', 'project'), ('student', 'student')], help_text='데이터 유형', max_length=20)),
                ('total_rows', models.IntegerField(help_text='파일 내 전체 행 수', validators=[django.core.validators.MinValueValidator(0)])),
                ('success_rows', models.IntegerField(help_text='성공적으로 처리된 행 수', validators=[django.core.validators.MinValueValidator(0)])),
                ('failed_rows', models.IntegerField(help_text='처리 실패한 행 수', validators=[django.core.validators.MinValueValidator(0)])),
                ('error_details', models.TextField(blank=True, help_text='오류 상세 정보 (JSON 형식)', null=True)),
                ('uploaded_by', models.ForeignKey(help_text='업로드한 사용자', on_delete=django.db.models.deletion.RESTRICT, related_name='upload_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upload_logs',
                'indexes': [models.Index(fields=['uploaded_by'], name='idx_upload_logs_uploaded_by'), models.Index(fields=['data_type'], name='idx_upload_logs_data_type'), models.Index(fields=['created_at'], name='idx_upload_logs_created_at')],
                'constraints': [models.CheckConstraint(condition=models.Q(('data_type__in', ['kpi', 'publication', 'project', 'student'])), name='check_data_type_valid'), models.CheckConstraint(condition=models.Q(('total_rows__gte', 0)), name='check_total_rows_positive'), models.CheckConstraint(condition=models.Q(('success_rows__gte', 0)), name='check_success_rows_positive'), models.CheckConstraint(condition=models.Q(('failed_rows__gte', 0)), name='check_failed_rows_positive')],
            },
        ),
    ]
