import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import { CurrentUserProvider } from "@/features/auth/context/current-user-context";
import { ErrorBoundary } from "@/components/error-boundary";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className="antialiased font-sans">
        <ErrorBoundary>
          <Providers>
            <CurrentUserProvider>
              {children}
              <Toaster />
            </CurrentUserProvider>
          </Providers>
        </ErrorBoundary>
      </body>
    </html>
  );
}
